version: "3"

services:
  mysql:  # https://hub.docker.com/_/mysql
    image: abbkit:0.0.1
    container_name: abbkit
    hostname: abbkit
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/data/docker/abbkit/:/var/lib/abbkit/" #Where to Store Data ,create a data directory on a suitable volume on your host system
    ports:
      - "8989:8080"
    restart: always
networks:
  default:
    external:
      name: abbkit